@startuml


state ServiceRequest{
state Draft : wait for opening
state Open : wait for interface 
state Payment{
  Unpaid: invoice Unpaid
  Paid : invoce paid
}
state InProgress : task in InProgress
state Completed : task complteted
state Closed : task closed
  
}


[*] --> Draft
Draft --> Open: Submit
Open -->  InProgress: Start Service
InProgress --> Unpaid
Paid --> Completed: Complete Service
Completed --> Closed: Close Request
Closed --> [*]: Reopen


Unpaid --> Paid: Make Payment
Paid --> [*]: Payment Received


@enduml
