@startuml

state ServiceRequest {
  state Draft : Wait for opening
  state Open : Wait for interface 
  state Payment {
    Unpaid: Invoice Unpaid
    Paid : Invoice Paid
  }
  state InProgress {
  PartsHandling : Handle Parts
  PerformingService : Performing Service
  RepairLogGenerated : Repair Log Generated
  }
  state Completed : Task completed
  
  state Closed : Task closed
}

[*] --> Draft
Draft --> Open: Submit by Technician
Open --> InProgress: Start Service
InProgress --> PartsHandling: Handle Parts
PartsHandling --> PerformingService: Perform Service
PerformingService --> RepairLogGenerated: Generate Repair Log
RepairLogGenerated --> Completed: Complete Service
Completed --> Unpaid
Paid --> Closed: Close Request
Closed --> [*]: Reopen

Unpaid --> Paid: Make Payment
Paid --> [*]: Payment Received

@enduml
