@startuml

participant "Customer" as Customer
participant "ServiceRequest" as ServiceRequest
participant "Technician" as Technician
participant "Invoice" as Invoice

Customer -> ServiceRequest: Create Service Request
activate ServiceRequest

ServiceRequest --> Customer: Service Request Created

Customer -> ServiceRequest: Review Service Request
activate ServiceRequest

ServiceRequest -> Technician: Assign Technician
activate Technician

Technician -> ServiceRequest: Technician Assigned
deactivate Technician

ServiceRequest -> Technician: Perform Service
activate Technician

Technician -> ServiceRequest: Service Performed
deactivate Technician
Customer -> ServiceRequest: Payment
ServiceRequest -> PaymentService: Payment Request
activate PaymentService
PaymentService -> ServiceRequest : Payment Confirmed
deactivate PaymentService
ServiceRequest -> Invoice: Generate Invoice
activate Invoice

Invoice --> ServiceRequest: Invoice Generated
deactivate Invoice

ServiceRequest --> Customer: Service Request Completed
deactivate ServiceRequest

@enduml
