@startuml
class CommonInfo {
  + name: String
  + price: Integer 
}
class Person {
  + name: String
  + surname: String
  + email: Email
  + phone_number: String
}
class ServiceRequest {
  + description: String
  + requested_by: Customer
  + owned_by: ServiceTechnician
  + requested_at: DateTime
}
class Invoice {
  + total_amount: Decimal
  + payment_status: Boolean 
  + service_request: ServiceRequest
  + part: Part
}
class Part {
  + description: String
  + quantity_in_stock: Integer 
}
class ServiceTechnician {
  + specialization: String
}
class Customer {
  + address_line1: String
  + address_line2: String
  + postal_code: String
  + city: String
  + state: String
  + country: String
}
CommonInfo --|> ServiceRequest
Person --|> ServiceRequest
ServiceRequest --|> Invoice
ServiceRequest *-- Customer : requested_by
ServiceRequest *-- ServiceTechnician : owned_by
Invoice *-- Part
Person --|> ServiceTechnician
Person --|> Customer
@enduml
