@startuml

participant "Customer" as Customer
participant "PaymentService" as PaymentService
participant "API" as ServiceRequest
participant "Technician" as Technician
participant "Invoice" as Invoice
participant "PartSupplier" as PartSupplier
participant "Warehouse" as Warehouse
participant "RepairLog" as RepairLog

Customer -> ServiceRequest: Create Service Request
activate ServiceRequest

ServiceRequest --> Customer: Service Request Created
deactivate ServiceRequest
Customer -> ServiceRequest: Review Service Request

activate ServiceRequest
ServiceRequest -> Technician: Assign Technician
activate Technician

Technician -> ServiceRequest: Technician Assigned
deactivate Technician

ServiceRequest -> Technician: Perform Service
activate Technician

Technician -> ServiceRequest: Service Performed
deactivate Technician

ServiceRequest -> PartSupplier: Order Parts
activate PartSupplier

PartSupplier --> ServiceRequest: Parts Ordered
deactivate PartSupplier

ServiceRequest -> Warehouse: Update Warehouse
activate Warehouse

Warehouse --> ServiceRequest: Warehouse Updated
deactivate Warehouse

ServiceRequest -> RepairLog: Generate Repair Log
activate RepairLog

RepairLog --> ServiceRequest: Repair Log Generated
deactivate RepairLog

ServiceRequest -> PaymentService: Information about receivables
activate PaymentService

PaymentService -> Customer: Payment Request
Customer -> PaymentService: Payment
PaymentService --> Customer: Payment Confirmed
PaymentService --> ServiceRequest: Payment Confirmed
deactivate PaymentService

ServiceRequest -> Invoice: Generate Invoice
activate Invoice

Invoice --> ServiceRequest: Invoice Generated
deactivate Invoice

ServiceRequest --> Customer: Service Request Completed
deactivate ServiceRequest

@enduml
