@startuml

participant "Customer" as Customer
participant "PaymentService" as PaymentService
participant "ServiceRequest" as ServiceRequest
participant "Technician" as Technician
participant "Invoice" as Invoice


Customer -> ServiceRequest: Create Service Request
activate ServiceRequest

ServiceRequest --> Customer: Service Request Created

Customer -> ServiceRequest: Review Service Request


ServiceRequest -> Technician: Assign Technician
activate Technician

Technician -> ServiceRequest: Technician Assigned
deactivate Technician

ServiceRequest -> Technician: Perform Service
activate Technician

Technician -> ServiceRequest: Service Performed
deactivate Technician

ServiceRequest -> PaymentService : Informations about receivables
activate PaymentService
PaymentService -> Customer: Payment Reques


Customer -> PaymentService: Payment

ServiceRequest <- PaymentService  : Payment Confirmed
deactivate PaymentService
ServiceRequest -> Invoice: Generate Invoice
activate Invoice

Invoice --> ServiceRequest: Invoice Generated
deactivate Invoice

ServiceRequest --> Customer: Service Request Completed
deactivate ServiceRequest

@enduml
