@startuml

(*)--> "Create Service Request by Cusotmer" as Create_Service_Request 
--> "Assign to Technician" as Assign_Technician
--> "Review Service Request" as Review_Service_Request 
if "Is correct request" then
-->[no] "Correcting Service Request" as Correct
--> "Approve Service Request" as Approve_SR
else
-->[yes] "Approve Service Request" as Approve_SR
if "Is approved" then
-down->[no] (*)
else 
-down->[yes] "Start Perform Service" as Start_Perform_Service
if "Cause of a problem is hardware part" then
--> [no]"Fix software problem" as FixSoft
-->  "Performing Service Request" as Performing
else 
--> [yes] if "Is part in warehouse" then
-->[yes] "Collect"
else 
-->[no] "Order Part" as Order
if "Is part available to order" then
--> [no] "Reject the Service Request"
-->  (*)
else
--> [yes] "Paid" as Paid 
--> "Wait for Delivery"
--> "Collect the Delivery"
--> "Add to Warehouse"
--> "Collect"
--> "Change Part"
--> "Performing Service Request" as Performing
--> "Ending Performing Service Request"
if "Is problem solved" then
-->[no] Start_Perform_Service
else 
--> [yes] "Complete repairing"
-->Generate Repair Log as "Generate_Repair_Log"
--> Generate Invoice : Complete Service
--> Payment : Paying for Parts and Service Requests
if "Payment completed" then
--> [no]"The parts and the repaired device remain the property of the service center"
-->(*)
else
--> [yes] if "Is customer satisfied" then
-->[yes] "Get Positive Customer Feedback" as Customer_Feedback
--> "Update Customer Record"
--> "Service Request Completed"
-->  (*)
else
-->[no] "Get Negative Customer Feedback"
-->"Review Feedback"
if "Is feedback founded"
--> [no](*)
else 
-->[yes]"Correcting Service Request"
-->Start_Perform_Service



@enduml
